import type { Metadata } from "next";
import { Montserrat, Raleway } from "next/font/google";
import "./globals.scss";
import { Suspense } from "react";
import Analytics from "@components/global/Analytics/Analytics";

const raleway = Raleway({ subsets: ['latin'] });
const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${raleway.className} ${montserrat.className}`}>
        {children}
        <Suspense>
          <Analytics />
        </Suspense>
      </body>
    </html>
  );
}
