import type { Metadata } from "next";
import "./globals.css";
import "./fonts.css";
import { Suspense } from "react";
import Analytics from "@components/Analytics/Analytics";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}
      <Suspense>
        <Analytics />
      </Suspense></body>
    </html>
  );
}
